/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(36b03f00-c934-11e4-8830-0800200c9a66)]
interface nsIDisplayDevice : nsISupports
{
  const long DISPLAY_TYPE_PRIMARY = 0;
  const long DISPLAY_TYPE_EXTERNAL = 1;
  const long DISPLAY_TYPE_VIRTUAL = 2;

  readonly attribute long type;

  readonly attribute boolean connected;

  readonly attribute long height;
  readonly attribute long width;
};
